export const HAND_DEFINITIONS: Record<string, { label: string; description: string; example: string }> = {
  'ping-hu': { label: 'Ping Hu (平胡)', description: 'All chows, no honors, pair is not a value tile', example: '1-2-3 / 4-5-6 / 7-8-9 / 2-3-4 + 9-9' },
  'duan-yao': { label: 'Duan Yao (断幺)', description: 'All simples — no 1s, 9s, or honor tiles', example: '2-3-4 / 5-6-7 / 3-4-5 / 6-7-8 + 2-2' },
  'men-qing': { label: 'Men Qing (门清)', description: 'Fully concealed hand won by ron', example: 'Win by discard with no revealed melds' },
  'flower-match': { label: 'Matching Flower/Season', description: 'Flower or season tile matching your seat number', example: 'Seat 3 holds Chrysanthemum (flower 3)' },
  'flower-full-set': { label: 'Full Flower/Season Set', description: 'All 4 flower tiles or all 4 season tiles', example: 'Plum + Orchid + Chrysanthemum + Bamboo' },
  'animal-yao': { label: 'Yao (动物对)', description: 'Holding both Rat+Cat or both Chicken+Worm', example: 'Rat + Cat = 1 yao' },
  'seat-wind-pong': { label: 'Seat Wind Pong', description: 'Pong of your own seat wind', example: 'South seat pongs South wind' },
  'prevailing-wind-pong': { label: 'Prevailing Wind Pong', description: 'Pong of the round prevailing wind', example: 'East round: pong East wind' },
  'dragon-pong': { label: 'Dragon Pong', description: 'Pong of any dragon tile', example: 'Pong of Red Dragon (中)' },
  'zimo': { label: 'Zi Mo (自摸)', description: 'Win by self-draw from the wall', example: 'Draw the winning tile yourself' },
  'dealer-bonus': { label: 'Dealer Bonus', description: 'Bonus for winning as the dealer', example: 'Win while you are the dealer (庄)' },
  'hunyi-se': { label: 'Hun Yi Se (混一色)', description: 'One suit plus honor tiles only', example: 'All bamboo + some winds/dragons' },
  'pong-pong': { label: 'Pong Pong (碰碰)', description: 'Four pongs or kongs (no chows)', example: '111 / 333 / 555 / 777 + 99' },
  '7-pairs': { label: '7 Pairs (七对)', description: 'Seven distinct pairs', example: '11 22 33 44 55 66 77' },
  'qing-yao-jiu': { label: 'Qing Yao Jiu (清幺九)', description: 'All terminals and/or honor tiles', example: '111 / 999 / EEE / SSS + NN' },
  'xiao-san-yuan': { label: 'Xiao San Yuan (小三元)', description: 'Two dragon pongs + one dragon pair', example: '中中中 / 发发发 + 白白' },
  'yi-se': { label: 'Yi Se (一色)', description: 'All tiles of the same suit, no honors', example: 'All bamboo tiles' },
  'lv-yi-se': { label: 'Lv Yi Se (绿一色)', description: 'All green tiles: 2/3/4/6/8 bamboo + green dragon only', example: '234 / 222 / 666 / 888 + 发发' },
  'xiao-si-xi': { label: 'Xiao Si Xi (小四喜)', description: 'Three wind pongs + one wind pair', example: 'EEE / SSS / WWW + NN' },
  'zi-yi-se': { label: 'Zi Yi Se (字一色)', description: 'All honor tiles (winds and/or dragons)', example: 'EEE / SSS / 中中中 / 发发发 + 白白' },
  'da-san-yuan': { label: 'Da San Yuan (大三元)', description: 'Three dragon pongs', example: '中中中 / 发发发 / 白白白 + any meld + pair' },
  'di-hu': { label: 'Di Hu (地胡)', description: 'Non-dealer wins on their very first draw or the first discard', example: 'Win immediately on first turn' },
  '13-orphans': { label: '13 Orphans (十三幺)', description: 'One of each terminal and honor tile plus one duplicate', example: '1m 9m 1s 9s 1p 9p E S W N 中 发 白 + 1 duplicate' },
  'da-si-xi': { label: 'Da Si Xi (大四喜)', description: 'Four wind pongs', example: 'EEEE / SSSS / WWWW / NNNN + pair' },
  'jiu-lian': { label: 'Jiu Lian Bao Deng (九莲宝灯)', description: 'Concealed 1-1-1-2-3-4-5-6-7-8-9-9-9 of one suit + any one tile', example: '1112345678999 (bamboo) + one more' },
  'tian-hu': { label: 'Tian Hu (天胡)', description: 'Dealer wins on their initial 14-tile hand before any discards', example: 'Complete hand immediately after deal' },
};
